Repository NREL/mappymatch, pull requests merged in 2022-10, with the labels that each got.

#152 Moving function into class method.
  docs/source/conf.py
  docs/source/index.rst
  docs/source/reference/constructs.rst
  docs/source/reference/maps.rst
  docs/source/reference/matchers.rst
  docs/source/reference/readers.rst
  docs/source/reference/utils.rst
  examples/line_snap_vs_lcss.py
  examples/match_one_trace.py
  mappymatch/constructs/geofence.py
  mappymatch/constructs/trace.py
  mappymatch/maps/nx/nx_map.py
  mappymatch/maps/nx/readers/osm_readers.py
  mappymatch/utils/geo.py
  mappymatch/utils/plot.py
  tests/test_osm.py
Labels: enhancement

#155 Improve local tooling
  .pre-commit-config.yaml
  docs/source/_static/_.txt
  docs/source/conf.py
  docs/source/general/contributing.rst
  docs/source/reference/maps.rst
  environment_dev.yml
  mypy.ini
  pyproject.toml
  tox.ini
Labels: documentation, enhancement

#154 update readme with new class methods
  README.md
  examples/line_snap_vs_lcss.py
  examples/match_one_trace.py
  mappymatch/maps/nx/nx_map.py
Labels: enhancement

#158 Update docs for version tags.
  docs/source/general/contributing.rst
Labels: documentation
